### ISSUE TITLE
您好，怎么修改默认 images 这个目录的名称？

### ISSUE THREAD

**Issue by yzg1943** [junbin123/load-markdwon-image#1]
这个脚本非常棒！怎么修改默认 images 这个目录的名称？

**Comment by junbin123** [comment]
重新安装下，load-markdown-image@1.0.7 版本支持了，eg.
`load-markdown-image test.md --fileName=xxx`
@yzg1943

**Comment by yzg1943** [comment]
感谢。
我刚更新到1.0.7后，使用 load-markdown-image test
这种目录命令批量下载，文件里的图片路径变成了 文件名+图片名，图片不显示了，不知道是不是我的问题，您有空可以测试下批量下载

**Comment by junbin123** [comment]
好的，我看下@yzg1943

**Comment by junbin123** [comment]
修好了，感谢，是个低级错误！@yzg1943 更新到1.0.8
